sudo: required
services:
    - docker

before_install:
    - docker build -t schuimax/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true schuimax/react-test npm test

after_success:
    - docker build -t schuimax/multi-client ./client
    - docker build -t schuimax/multi-nginx ./nginx
    - docker build -t schuimax/multi-server ./server
    - docker build -t schuimax/multi-worker ./worker

# login to docker CLI    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# push prod images to docker hub
    - docker push schuimax/multi-client
    - docker push schuimax/multi-nginx
    - docker push schuimax/multi-server
    - docker push schuimax/multi-worker

# deploy

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-935966686392
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY