sudo: required
services:
    - docker

before_install:
    - docker build -t schuimax/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true schuimax/react-test npm test

after_success:
    - docker build -t schuimax/multi-client ./client
    - docker build -t schuimax/multi-nginx ./nginx
    - docker build -t schuimax/multi-server ./server
    - docker build -t schuimax/multi-worker ./worker

# login to docker CLI    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# push prod images to docker hub
    - docker push schuimax/multi-client
    - docker push schuimax/multi-nginx
    - docker push schuimax/multi-server
    - docker push schuimax/multi-worker